title: Wild Alentejo
description: Vida off-grid no semiárido — Mértola, Portugal
url: "https://wildalentejo.pt"  
markdown: kramdown

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /logbook/:year/:month/:day/:title/

plugins:
  - jekyll-sitemap  
  - jekyll-seo-tag          
  - jekyll-redirect-from   
