title: Wild Alentejo
description: Vida off-grid no semiárido — Mértola, Portugal
url: "https://wildalentejo.pt"

# permalink só para os posts
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: /logbook/:year/:month/:day/:title/

markdown: kramdown
